2025-05-20 07:59:40.479 [main] INFO  base.BaseTest - Setting up test suite: Surefire suite
2025-05-20 07:59:40.495 [main] INFO  config.ConfigurationManager - Using environment: qa
2025-05-20 07:59:40.498 [main] WARN  config.PropertyManager - Could not find properties file: config/application-qa.properties
2025-05-20 07:59:40.507 [main] INFO  report.AllureReportManager - Setting up Allure environment information
2025-05-20 07:59:40.527 [main] INFO  base.BaseTest - Test suite setup completed
2025-05-20 07:59:40.544 [main] INFO  base.TestListener - Test Suite Started: Surefire test
2025-05-20 07:59:40.545 [main] INFO  base.TestListener - Included groups: 
2025-05-20 07:59:40.545 [main] INFO  base.TestListener - Excluded groups: 
2025-05-20 07:59:40.586 [main] INFO  base.BaseTest - Setting up test class: UserAPITest
2025-05-20 07:59:40.588 [main] INFO  tests.UserAPITest - Setting up User API tests for JSONPlaceholder API
2025-05-20 07:59:40.632 [main] INFO  base.BaseTest - Setting up test suite: Test Automation Suite
2025-05-20 07:59:40.641 [main] INFO  config.ConfigurationManager - Using environment: qa
2025-05-20 07:59:40.642 [main] WARN  config.PropertyManager - Could not find properties file: config/application-qa.properties
2025-05-20 07:59:40.644 [main] INFO  report.AllureReportManager - Setting up Allure environment information
2025-05-20 07:59:40.652 [main] INFO  base.BaseTest - Test suite setup completed
2025-05-20 07:59:40.656 [main] INFO  base.BaseTest - Starting test: testFetchUserById
2025-05-20 07:59:40.658 [main] INFO  utils.LoggerUtils - Setting up logging context for test: testFetchUserById, thread: 1
2025-05-20 07:59:40.672 [TestNG-tests-1] INFO  base.TestListener - Test Suite Started: API Tests
2025-05-20 07:59:40.675 [TestNG-tests-1] INFO  base.TestListener - Included groups: api
2025-05-20 07:59:40.675 [TestNG-tests-1] INFO  base.TestListener - Excluded groups: 
2025-05-20 07:59:40.680 [TestNG-tests-2] INFO  base.TestListener - Test Suite Started: Smoke Tests
2025-05-20 07:59:40.681 [TestNG-tests-2] INFO  base.TestListener - Included groups: smoke
2025-05-20 07:59:40.681 [TestNG-tests-2] INFO  base.TestListener - Excluded groups: 
2025-05-20 07:59:40.719 [TestNG-tests-3] INFO  base.TestListener - Test Suite Started: Regression Tests
2025-05-20 07:59:40.720 [TestNG-tests-3] INFO  base.TestListener - Included groups: regression
2025-05-20 07:59:40.720 [TestNG-tests-3] INFO  base.TestListener - Excluded groups: 
2025-05-20 07:59:40.746 [TestNG-tests-1] INFO  base.BaseTest - Setting up test class: UserAPITest
2025-05-20 07:59:40.747 [TestNG-tests-1] INFO  tests.UserAPITest - Setting up User API tests for JSONPlaceholder API
2025-05-20 07:59:40.765 [TestNG-test=Regression Tests-1] INFO  base.BaseTest - Setting up test class: UserAPITest
2025-05-20 07:59:40.768 [TestNG-test=Regression Tests-1] INFO  tests.UserAPITest - Setting up User API tests for JSONPlaceholder API
2025-05-20 07:59:40.777 [TestNG-test=Regression Tests-3] INFO  base.BaseTest - Starting test: testDeleteUser
2025-05-20 07:59:40.778 [TestNG-tests-1] INFO  base.BaseTest - Starting test: testFetchUserById
2025-05-20 07:59:40.779 [TestNG-test=Regression Tests-1] INFO  base.BaseTest - Starting test: testCreateUser
2025-05-20 07:59:40.780 [TestNG-test=Regression Tests-3] INFO  utils.LoggerUtils - Setting up logging context for test: testDeleteUser, thread: 40
2025-05-20 07:59:40.780 [TestNG-tests-1] INFO  utils.LoggerUtils - Setting up logging context for test: testFetchUserById, thread: 34
2025-05-20 07:59:40.780 [TestNG-test=Regression Tests-1] INFO  utils.LoggerUtils - Setting up logging context for test: testCreateUser, thread: 37
2025-05-20 07:59:40.780 [TestNG-test=Regression Tests-2] INFO  base.BaseTest - Starting test: testUpdateUser
2025-05-20 07:59:40.781 [TestNG-test=Regression Tests-2] INFO  utils.LoggerUtils - Setting up logging context for test: testUpdateUser, thread: 38
2025-05-20 07:59:40.782 [TestNG-test=Smoke Tests-1] INFO  base.BaseTest - Setting up test class: UserAPITest
2025-05-20 07:59:40.791 [TestNG-test=Smoke Tests-1] INFO  tests.UserAPITest - Setting up User API tests for JSONPlaceholder API
2025-05-20 07:59:40.840 [TestNG-test=Smoke Tests-1] INFO  base.BaseTest - Starting test: testFetchUserById
2025-05-20 07:59:40.841 [TestNG-test=Smoke Tests-1] INFO  utils.LoggerUtils - Setting up logging context for test: testFetchUserById, thread: 39
2025-05-20 07:59:40.843 [TestNG-test=Smoke Tests-2] INFO  base.BaseTest - Starting test: testFetchNonExistentUser
2025-05-20 07:59:40.844 [TestNG-test=Smoke Tests-2] INFO  utils.LoggerUtils - Setting up logging context for test: testFetchNonExistentUser, thread: 41
2025-05-20 07:59:41.852 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2025-05-20 07:59:41.865 [TestNG-test=Regression Tests-2] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Starting...
2025-05-20 07:59:41.866 [TestNG-test=Smoke Tests-2] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Starting...
2025-05-20 07:59:41.867 [TestNG-test=Regression Tests-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2025-05-20 07:59:41.867 [TestNG-tests-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-6 - Starting...
2025-05-20 07:59:41.867 [TestNG-test=Regression Tests-3] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
2025-05-20 07:59:41.865 [TestNG-test=Smoke Tests-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-5 - Starting...
2025-05-20 07:59:55.361 [main] INFO  base.BaseTest - Setting up test suite: Surefire suite
2025-05-20 07:59:55.370 [main] INFO  config.ConfigurationManager - Using environment: qa
2025-05-20 07:59:55.371 [main] WARN  config.PropertyManager - Could not find properties file: config/application-qa.properties
2025-05-20 07:59:55.373 [main] INFO  report.AllureReportManager - Setting up Allure environment information
2025-05-20 07:59:55.381 [main] INFO  base.BaseTest - Test suite setup completed
2025-05-20 07:59:55.387 [main] INFO  base.TestListener - Test Suite Started: Surefire test
2025-05-20 07:59:55.387 [main] INFO  base.TestListener - Included groups: 
2025-05-20 07:59:55.388 [main] INFO  base.TestListener - Excluded groups: 
2025-05-20 07:59:55.416 [main] INFO  base.BaseTest - Setting up test class: UserAPITest
2025-05-20 07:59:55.417 [main] INFO  tests.UserAPITest - Setting up User API tests for JSONPlaceholder API
2025-05-20 07:59:55.433 [main] INFO  base.BaseTest - Starting test: testFetchUserById
2025-05-20 07:59:55.435 [main] INFO  utils.LoggerUtils - Setting up logging context for test: testFetchUserById, thread: 1
2025-05-20 07:59:56.012 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2025-05-20 08:00:12.922 [TestNG-test=Regression Tests-3] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:00:12.922 [TestNG-test=Smoke Tests-2] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-4 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:00:12.922 [TestNG-tests-1] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-6 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:00:12.922 [TestNG-test=Regression Tests-2] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:00:12.922 [TestNG-test=Regression Tests-1] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:00:12.922 [TestNG-test=Smoke Tests-1] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-5 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:00:13.213 [TestNG-test=Regression Tests-3] INFO  base.TestListener - Test Started: testDeleteUser (tests.UserAPITest)
2025-05-20 08:00:13.215 [TestNG-test=Regression Tests-1] INFO  base.TestListener - Test Started: testCreateUser (tests.UserAPITest)
2025-05-20 08:00:13.216 [TestNG-test=Smoke Tests-2] INFO  base.TestListener - Test Started: testFetchNonExistentUser (tests.UserAPITest)
2025-05-20 08:00:13.217 [TestNG-test=Smoke Tests-1] INFO  base.TestListener - Test Started: testFetchUserById (tests.UserAPITest)
2025-05-20 08:00:13.219 [TestNG-tests-1] INFO  base.TestListener - Test Started: testFetchUserById (tests.UserAPITest)
2025-05-20 08:00:13.216 [TestNG-test=Smoke Tests-2] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.219 [TestNG-test=Regression Tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.219 [TestNG-test=Regression Tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.221 [TestNG-test=Smoke Tests-2] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.216 [TestNG-test=Regression Tests-3] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.227 [TestNG-test=Regression Tests-3] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.228 [TestNG-test=Regression Tests-2] INFO  base.TestListener - Test Started: testUpdateUser (tests.UserAPITest)
2025-05-20 08:00:13.228 [TestNG-test=Regression Tests-1] INFO  base.TestListener - Test Skipped: testCreateUser
2025-05-20 08:00:13.228 [TestNG-test=Regression Tests-2] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.229 [TestNG-test=Regression Tests-1] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:00:13.229 [TestNG-test=Regression Tests-2] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.229 [TestNG-test=Regression Tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:00:13.230 [TestNG-test=Regression Tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:00:13.233 [TestNG-test=Regression Tests-1] INFO  base.BaseTest - Finished test: testCreateUser - UNKNOWN
2025-05-20 08:00:13.234 [TestNG-test=Regression Tests-3] INFO  base.TestListener - Test Skipped: testDeleteUser
2025-05-20 08:00:13.234 [TestNG-test=Regression Tests-2] INFO  base.TestListener - Test Skipped: testUpdateUser
2025-05-20 08:00:13.235 [TestNG-test=Regression Tests-2] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:00:13.235 [TestNG-test=Regression Tests-3] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:00:13.236 [TestNG-test=Regression Tests-3] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:00:13.236 [TestNG-test=Regression Tests-1] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:00:13.236 [TestNG-test=Regression Tests-3] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:00:13.235 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.237 [TestNG-test=Regression Tests-2] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:00:13.237 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.237 [TestNG-test=Regression Tests-3] INFO  base.BaseTest - Finished test: testDeleteUser - UNKNOWN
2025-05-20 08:00:13.238 [TestNG-test=Regression Tests-3] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:00:13.238 [TestNG-test=Smoke Tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.239 [TestNG-test=Smoke Tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:13.241 [TestNG-test=Smoke Tests-2] INFO  base.TestListener - Test Skipped: testFetchNonExistentUser
2025-05-20 08:00:13.241 [TestNG-test=Smoke Tests-2] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:00:13.241 [TestNG-test=Smoke Tests-2] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:00:13.241 [TestNG-test=Smoke Tests-2] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:00:13.237 [TestNG-test=Regression Tests-2] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:00:13.245 [TestNG-test=Smoke Tests-2] INFO  base.BaseTest - Finished test: testFetchNonExistentUser - UNKNOWN
2025-05-20 08:00:13.245 [TestNG-test=Regression Tests-2] INFO  base.BaseTest - Finished test: testUpdateUser - UNKNOWN
2025-05-20 08:00:13.248 [TestNG-tests-1] INFO  base.TestListener - Test Skipped: testFetchUserById
2025-05-20 08:00:13.248 [TestNG-test=Regression Tests-2] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:00:13.249 [TestNG-tests-1] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:00:13.250 [TestNG-test=Smoke Tests-1] INFO  base.TestListener - Test Skipped: testFetchUserById
2025-05-20 08:00:13.245 [TestNG-test=Smoke Tests-2] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:00:13.257 [TestNG-test=Smoke Tests-1] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:00:13.257 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:00:13.257 [TestNG-test=Smoke Tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:00:13.258 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:00:13.259 [TestNG-test=Smoke Tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:00:13.261 [TestNG-tests-1] INFO  base.BaseTest - Finished test: testFetchUserById - UNKNOWN
2025-05-20 08:00:13.261 [TestNG-test=Smoke Tests-1] INFO  base.BaseTest - Finished test: testFetchUserById - UNKNOWN
2025-05-20 08:00:13.262 [TestNG-tests-1] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:00:13.262 [TestNG-test=Smoke Tests-1] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:00:13.265 [TestNG-test=Regression Tests-3] INFO  base.BaseTest - Tearing down test class: UserAPITest
2025-05-20 08:00:13.266 [TestNG-tests-1] INFO  base.BaseTest - Starting test: testFetchNonExistentUser
2025-05-20 08:00:13.267 [TestNG-test=Smoke Tests-1] INFO  base.BaseTest - Tearing down test class: UserAPITest
2025-05-20 08:00:13.267 [TestNG-tests-1] INFO  utils.LoggerUtils - Setting up logging context for test: testFetchNonExistentUser, thread: 34
2025-05-20 08:00:13.270 [TestNG-tests-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-7 - Starting...
2025-05-20 08:00:13.301 [TestNG-tests-2] INFO  base.TestListener - Test Suite Finished: Smoke Tests
2025-05-20 08:00:13.302 [TestNG-tests-3] INFO  base.TestListener - Test Suite Finished: Regression Tests
2025-05-20 08:00:13.303 [TestNG-tests-2] INFO  base.TestListener - Passed tests: 0
2025-05-20 08:00:13.303 [TestNG-tests-3] INFO  base.TestListener - Passed tests: 0
2025-05-20 08:00:13.304 [TestNG-tests-2] INFO  base.TestListener - Failed tests: 0
2025-05-20 08:00:13.304 [TestNG-tests-3] INFO  base.TestListener - Failed tests: 0
2025-05-20 08:00:13.304 [TestNG-tests-2] INFO  base.TestListener - Skipped tests: 2
2025-05-20 08:00:13.304 [TestNG-tests-3] INFO  base.TestListener - Skipped tests: 3
2025-05-20 08:00:13.304 [TestNG-tests-2] INFO  base.TestListener - Total execution time: 32588 ms
2025-05-20 08:00:13.304 [TestNG-tests-3] INFO  base.TestListener - Total execution time: 32547 ms
2025-05-20 08:00:26.817 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.run(SuiteRunner.java:330) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuites(TestNG.java:1099) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.run(TestNG.java:1067) [testng-7.7.1.jar:7.7.1]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495) [surefire-booter-3.1.2.jar:3.1.2]
2025-05-20 08:00:26.992 [main] INFO  base.TestListener - Test Started: testFetchUserById (tests.UserAPITest)
2025-05-20 08:00:26.993 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:26.994 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:27.014 [main] INFO  base.TestListener - Test Skipped: testFetchUserById
2025-05-20 08:00:27.014 [main] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:00:27.016 [main] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:00:27.017 [main] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:00:27.019 [main] INFO  base.BaseTest - Finished test: testFetchUserById - UNKNOWN
2025-05-20 08:00:27.022 [main] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:00:27.048 [main] INFO  base.BaseTest - Starting test: testFetchNonExistentUser
2025-05-20 08:00:27.049 [main] INFO  utils.LoggerUtils - Setting up logging context for test: testFetchNonExistentUser, thread: 1
2025-05-20 08:00:27.051 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
2025-05-20 08:00:43.799 [TestNG-tests-1] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-7 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:00:43.806 [TestNG-tests-1] INFO  base.TestListener - Test Started: testFetchNonExistentUser (tests.UserAPITest)
2025-05-20 08:00:43.807 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:43.807 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:43.812 [TestNG-tests-1] INFO  base.TestListener - Test Skipped: testFetchNonExistentUser
2025-05-20 08:00:43.813 [TestNG-tests-1] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:00:43.813 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:00:43.813 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:00:43.814 [TestNG-tests-1] INFO  base.BaseTest - Finished test: testFetchNonExistentUser - UNKNOWN
2025-05-20 08:00:43.814 [TestNG-tests-1] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:00:43.817 [TestNG-tests-1] INFO  base.BaseTest - Starting test: testCreateUser
2025-05-20 08:00:43.817 [TestNG-tests-1] INFO  utils.LoggerUtils - Setting up logging context for test: testCreateUser, thread: 34
2025-05-20 08:00:43.819 [TestNG-tests-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-8 - Starting...
2025-05-20 08:00:57.578 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.run(SuiteRunner.java:330) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuites(TestNG.java:1099) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.run(TestNG.java:1067) [testng-7.7.1.jar:7.7.1]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495) [surefire-booter-3.1.2.jar:3.1.2]
2025-05-20 08:00:57.589 [main] INFO  base.TestListener - Test Started: testFetchNonExistentUser (tests.UserAPITest)
2025-05-20 08:00:57.589 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:57.590 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:00:57.594 [main] INFO  base.TestListener - Test Skipped: testFetchNonExistentUser
2025-05-20 08:00:57.595 [main] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:00:57.595 [main] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:00:57.595 [main] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:00:57.596 [main] INFO  base.BaseTest - Finished test: testFetchNonExistentUser - UNKNOWN
2025-05-20 08:00:57.597 [main] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:00:57.599 [main] INFO  base.BaseTest - Starting test: testCreateUser
2025-05-20 08:00:57.599 [main] INFO  utils.LoggerUtils - Setting up logging context for test: testCreateUser, thread: 1
2025-05-20 08:00:57.600 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Starting...
2025-05-20 08:01:14.344 [TestNG-tests-1] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-8 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:01:14.351 [TestNG-tests-1] INFO  base.TestListener - Test Started: testCreateUser (tests.UserAPITest)
2025-05-20 08:01:14.351 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:01:14.352 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:01:14.355 [TestNG-tests-1] INFO  base.TestListener - Test Skipped: testCreateUser
2025-05-20 08:01:14.355 [TestNG-tests-1] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:01:14.355 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:01:14.355 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:01:14.356 [TestNG-tests-1] INFO  base.BaseTest - Finished test: testCreateUser - UNKNOWN
2025-05-20 08:01:14.356 [TestNG-tests-1] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:01:14.359 [TestNG-tests-1] INFO  base.BaseTest - Starting test: testUpdateUser
2025-05-20 08:01:14.359 [TestNG-tests-1] INFO  utils.LoggerUtils - Setting up logging context for test: testUpdateUser, thread: 34
2025-05-20 08:01:14.361 [TestNG-tests-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-9 - Starting...
2025-05-20 08:01:28.126 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.run(SuiteRunner.java:330) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuites(TestNG.java:1099) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.run(TestNG.java:1067) [testng-7.7.1.jar:7.7.1]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495) [surefire-booter-3.1.2.jar:3.1.2]
2025-05-20 08:01:28.135 [main] INFO  base.TestListener - Test Started: testCreateUser (tests.UserAPITest)
2025-05-20 08:01:28.136 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:01:28.136 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:01:28.140 [main] INFO  base.TestListener - Test Skipped: testCreateUser
2025-05-20 08:01:28.140 [main] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:01:28.140 [main] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:01:28.141 [main] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:01:28.142 [main] INFO  base.BaseTest - Finished test: testCreateUser - UNKNOWN
2025-05-20 08:01:28.142 [main] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:01:28.144 [main] INFO  base.BaseTest - Starting test: testUpdateUser
2025-05-20 08:01:28.144 [main] INFO  utils.LoggerUtils - Setting up logging context for test: testUpdateUser, thread: 1
2025-05-20 08:01:28.146 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Starting...
2025-05-20 08:01:44.883 [TestNG-tests-1] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-9 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:01:44.888 [TestNG-tests-1] INFO  base.TestListener - Test Started: testUpdateUser (tests.UserAPITest)
2025-05-20 08:01:44.889 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:01:44.889 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:01:44.892 [TestNG-tests-1] INFO  base.TestListener - Test Skipped: testUpdateUser
2025-05-20 08:01:44.892 [TestNG-tests-1] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:01:44.892 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:01:44.892 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:01:44.893 [TestNG-tests-1] INFO  base.BaseTest - Finished test: testUpdateUser - UNKNOWN
2025-05-20 08:01:44.893 [TestNG-tests-1] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:01:44.895 [TestNG-tests-1] INFO  base.BaseTest - Starting test: testDeleteUser
2025-05-20 08:01:44.895 [TestNG-tests-1] INFO  utils.LoggerUtils - Setting up logging context for test: testDeleteUser, thread: 34
2025-05-20 08:01:44.896 [TestNG-tests-1] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-10 - Starting...
2025-05-20 08:01:58.673 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-4 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.run(SuiteRunner.java:330) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuites(TestNG.java:1099) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.run(TestNG.java:1067) [testng-7.7.1.jar:7.7.1]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495) [surefire-booter-3.1.2.jar:3.1.2]
2025-05-20 08:01:58.681 [main] INFO  base.TestListener - Test Started: testUpdateUser (tests.UserAPITest)
2025-05-20 08:01:58.681 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:01:58.682 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:01:58.686 [main] INFO  base.TestListener - Test Skipped: testUpdateUser
2025-05-20 08:01:58.686 [main] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:01:58.686 [main] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:01:58.686 [main] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:01:58.687 [main] INFO  base.BaseTest - Finished test: testUpdateUser - UNKNOWN
2025-05-20 08:01:58.687 [main] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:01:58.689 [main] INFO  base.BaseTest - Starting test: testDeleteUser
2025-05-20 08:01:58.689 [main] INFO  utils.LoggerUtils - Setting up logging context for test: testDeleteUser, thread: 1
2025-05-20 08:01:58.690 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-5 - Starting...
2025-05-20 08:02:15.420 [TestNG-tests-1] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-10 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58) ~[testng-7.7.1.jar:7.7.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
2025-05-20 08:02:15.426 [TestNG-tests-1] INFO  base.TestListener - Test Started: testDeleteUser (tests.UserAPITest)
2025-05-20 08:02:15.426 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:02:15.426 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:02:15.431 [TestNG-tests-1] INFO  base.TestListener - Test Skipped: testDeleteUser
2025-05-20 08:02:15.431 [TestNG-tests-1] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:02:15.432 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:02:15.432 [TestNG-tests-1] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:02:15.433 [TestNG-tests-1] INFO  base.BaseTest - Finished test: testDeleteUser - UNKNOWN
2025-05-20 08:02:15.433 [TestNG-tests-1] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:02:15.435 [TestNG-tests-1] INFO  base.BaseTest - Tearing down test class: UserAPITest
2025-05-20 08:02:15.454 [TestNG-tests-1] INFO  base.TestListener - Test Suite Finished: API Tests
2025-05-20 08:02:15.454 [TestNG-tests-1] INFO  base.TestListener - Passed tests: 0
2025-05-20 08:02:15.454 [TestNG-tests-1] INFO  base.TestListener - Failed tests: 0
2025-05-20 08:02:15.455 [TestNG-tests-1] INFO  base.TestListener - Skipped tests: 5
2025-05-20 08:02:15.455 [TestNG-tests-1] INFO  base.TestListener - Total execution time: 154767 ms
2025-05-20 08:02:15.456 [main] INFO  base.BaseTest - Tearing down test suite: Test Automation Suite
2025-05-20 08:02:29.215 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-5 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:189) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.run(SuiteRunner.java:330) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuites(TestNG.java:1099) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.run(TestNG.java:1067) [testng-7.7.1.jar:7.7.1]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495) [surefire-booter-3.1.2.jar:3.1.2]
2025-05-20 08:02:29.232 [main] INFO  base.TestListener - Test Started: testDeleteUser (tests.UserAPITest)
2025-05-20 08:02:29.235 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:02:29.236 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:02:29.244 [main] INFO  base.TestListener - Test Skipped: testDeleteUser
2025-05-20 08:02:29.244 [main] INFO  base.TestListener - Test skipped reason: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2025-05-20 08:02:29.245 [main] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:02:29.245 [main] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:02:29.246 [main] INFO  base.BaseTest - Finished test: testDeleteUser - UNKNOWN
2025-05-20 08:02:29.246 [main] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:02:29.248 [main] INFO  base.BaseTest - Tearing down test class: UserAPITest
2025-05-20 08:02:29.343 [main] INFO  base.TestListener - Test Suite Finished: Surefire test
2025-05-20 08:02:29.343 [main] INFO  base.TestListener - Passed tests: 0
2025-05-20 08:02:29.343 [main] INFO  base.TestListener - Failed tests: 0
2025-05-20 08:02:29.343 [main] INFO  base.TestListener - Skipped tests: 5
2025-05-20 08:02:29.343 [main] INFO  base.TestListener - Total execution time: 153865 ms
2025-05-20 08:02:29.350 [main] INFO  base.BaseTest - Tearing down test suite: Surefire suite
2025-05-20 08:58:18.056 [main] INFO  base.BaseTest - Setting up test suite: Surefire suite
2025-05-20 08:58:18.064 [main] INFO  config.ConfigurationManager - Using environment: qa
2025-05-20 08:58:18.066 [main] WARN  config.PropertyManager - Could not find properties file: config/application-qa.properties
2025-05-20 08:58:18.067 [main] INFO  report.AllureReportManager - Setting up Allure environment information
2025-05-20 08:58:18.079 [main] INFO  base.BaseTest - Test suite setup completed
2025-05-20 08:58:18.087 [main] INFO  base.TestListener - Test Suite Started: Surefire test
2025-05-20 08:58:18.087 [main] INFO  base.TestListener - Included groups: 
2025-05-20 08:58:18.088 [main] INFO  base.TestListener - Excluded groups: 
2025-05-20 08:58:18.120 [main] INFO  base.BaseTest - Setting up test class: UserAPITest
2025-05-20 08:58:18.122 [main] INFO  tests.UserAPITest - Setting up User API tests for JSONPlaceholder API
2025-05-20 08:58:18.138 [main] INFO  base.BaseTest - Starting test: testFetchUserById
2025-05-20 08:58:18.140 [main] INFO  utils.LoggerUtils - Setting up logging context for test: testFetchUserById, thread: 1
2025-05-20 08:58:18.799 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2025-05-20 08:58:49.631 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerException.convertConnectExceptionToSQLServerException(SQLServerException.java:288) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2574) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:715) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3427) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229) ~[mssql-jdbc-12.2.0.jre11.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-5.0.1.jar:?]
	at db.sql.HikariCPDataSource.<init>(HikariCPDataSource.java:49) ~[classes/:?]
	at db.sql.SqlClient.<init>(SqlClient.java:42) ~[classes/:?]
	at base.BaseTest.initializeDatabaseClients(BaseTest.java:191) ~[classes/:?]
	at base.BaseTest.setupMethod(BaseTest.java:119) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.run(SuiteRunner.java:330) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuites(TestNG.java:1099) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.run(TestNG.java:1067) [testng-7.7.1.jar:7.7.1]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495) [surefire-booter-3.1.2.jar:3.1.2]
2025-05-20 08:58:49.648 [main] WARN  base.BaseTest - Failed to initialize SQL client: Failed to initialize pool: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".. Tests will continue without SQL database access.
2025-05-20 08:58:49.653 [main] WARN  config.ConfigurationManager - Property 'db.cosmos.container' not found in any configuration source
2025-05-20 08:58:49.654 [main] WARN  base.BaseTest - Cosmos DB configuration is incomplete. Missing database name or container name.
2025-05-20 08:58:49.776 [main] INFO  base.TestListener - Test Started: testFetchUserById (tests.UserAPITest)
2025-05-20 08:58:49.782 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:58:49.782 [main] ERROR io.qameta.allure.AllureLifecycle - Could not update test case: no test case running
2025-05-20 08:58:49.871 [main] INFO  tests.UserAPITest - Fetching user with ID: 1
2025-05-20 08:58:50.010 [main] ERROR io.qameta.allure.util.NamingUtils - Could not find parameter endpoint
2025-05-20 08:58:50.121 [main] INFO  utils.LoggerUtils - 
-------- REQUEST --------
Method: GET
URL: /users/{id}
Headers: {Accept=application/json}
-------------------------

2025-05-20 08:58:51.600 [main] ERROR base.TestListener - Test Failed: testFetchUserById
2025-05-20 08:58:51.600 [main] ERROR base.TestListener - Test failure reason: 
java.lang.RuntimeException: Request failed after 3 retries
	at rest.RestApiClient.executeWithRetry(RestApiClient.java:285) ~[classes/:?]
	at rest.RestApiClient.executeRequest(RestApiClient.java:232) ~[classes/:?]
	at rest.RequestBuilder.send(RequestBuilder.java:280) ~[classes/:?]
	at tests.UserAPITest.testFetchUserById(UserAPITest.java:46) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.7.1.jar:7.7.1]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.7.1.jar:7.7.1]
	at java.util.ArrayList.forEach(ArrayList.java:1596) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:829) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestRunner.run(TestRunner.java:602) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunner.run(SuiteRunner.java:330) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.7.1.jar:7.7.1]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.runSuites(TestNG.java:1099) [testng-7.7.1.jar:7.7.1]
	at org.testng.TestNG.run(TestNG.java:1067) [testng-7.7.1.jar:7.7.1]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137) [surefire-testng-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507) [surefire-booter-3.1.2.jar:3.1.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495) [surefire-booter-3.1.2.jar:3.1.2]
Caused by: java.lang.NullPointerException: Cannot invoke method log() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:95) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130) ~[groovy-4.0.6.jar:4.0.6]
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1683) ~[rest-assured-5.3.0.jar:?]
	at io.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy) ~[rest-assured-5.3.0.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1348) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792) ~[groovy-4.0.6.jar:4.0.6]
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy) ~[rest-assured-5.3.0.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203) ~[groovy-4.0.6.jar:4.0.6]
	at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1710) ~[rest-assured-5.3.0.jar:?]
	at io.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy) ~[rest-assured-5.3.0.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1348) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792) ~[groovy-4.0.6.jar:4.0.6]
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy) ~[rest-assured-5.3.0.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203) ~[groovy-4.0.6.jar:4.0.6]
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:172) ~[rest-assured-5.3.0.jar:?]
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy) ~[rest-assured-5.3.0.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1348) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009) ~[groovy-4.0.6.jar:4.0.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792) ~[groovy-4.0.6.jar:4.0.6]
	at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy) ~[rest-assured-5.3.0.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57) ~[groovy-4.0.6.jar:4.0.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185) ~[groovy-4.0.6.jar:4.0.6]
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:256) ~[rest-assured-5.3.0.jar:?]
	at io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy) ~[rest-assured-5.3.0.jar:?]
	at rest.RestApiClient.lambda$executeRequest$0(RestApiClient.java:214) ~[classes/:?]
	at rest.RestApiClient.executeWithRetry(RestApiClient.java:249) ~[classes/:?]
	... 34 more
2025-05-20 08:58:51.602 [main] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
2025-05-20 08:58:51.603 [main] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
2025-05-20 08:58:51.603 [main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running
2025-05-20 08:58:51.604 [main] INFO  base.BaseTest - Finished test: testFetchUserById - FAILED
2025-05-20 08:58:51.605 [main] DEBUG utils.LoggerUtils - Clearing thread context data
2025-05-20 08:58:51.609 [main] INFO  base.BaseTest - Starting test: testFetchNonExistentUser
2025-05-20 08:58:51.609 [main] INFO  utils.LoggerUtils - Setting up logging context for test: testFetchNonExistentUser, thread: 1
2025-05-20 08:58:51.610 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
